version: '3'
services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    image: mdo6180/mlflow-component:latest
    container_name: mlflow-test
    command: python main.py
    ports:
      - "8001:8000"
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./anacostia-artifacts:/artifacts

# build and run all image:
# $ docker-compose up --build

# remove container:
# $ docker-compose down

# display logs when building specific images
# docker-compose build --no-cache --progress=plain xrca-prod

# build specific container 
# docker-compose up --build <target name>