version: '3'
services:
  mlflow-prod:
    build:
      context: ./mlflow
      target: prod
    image: mdo6180/mlflow-component:latest

  mlflow-dev:
    build:
      context: ./mlflow
      target: dev
    image: mdo6180/mlflow-dev:latest
    container_name: Anacostia-MLflow
    command: python main.py
    ports:
      - "8001:8000"
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./anacostia-artifacts:/artifacts
      - ./mlflow:/app

# build and run all image:
# $ docker-compose up --build

# remove container:
# $ docker-compose down

# display logs when building specific images
# docker-compose build --no-cache --progress=plain xrca-prod

# build specific container 
# docker-compose up --build <target name>