version: '3'
services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    image: mdo6180/mlflow
    container_name: mlflow-test
    ports:
      - "8000:5000"
    volumes:
      - ./storage:/app/storage

# build and run all image:
# $ docker-compose up --build

# remove container:
# $ docker-compose down

# display logs when building specific images
# docker-compose build --no-cache --progress=plain xrca-prod

# build specific container 
# docker-compose up --build <target name>