version: '3'
pipeline:
  name: imagenet-resnet
  stages:
    - train:
        tools:
          - mlflow:
              environment: local
      schedule: "0 0 * * *"
    - deploy:
        tools:
          - seldon core:
              environment: executor
        schedule: "0 0 * * *"
    - monitor:
        tools:
          - ama:
              parameters:
                - path-length: 30
          - weave:
              parameters:
                - epochs: 50