version: '3'
pipeline:
  name: imagenet-resnet
  stages:
    - train:
        tools:
          - mlflow:
              environment: local
              version: 2.3.0
        schedule: "0 0 * * *"
    - deploy:
        tools:
          - seldon core:
              environment: executor
              version: 1.2.0
        schedule: "0 0 * * *"
    - monitor:
        tools:
          - ama:
              version: 0.2.0
              parameters:
                - path-length: 30
          - weave:
              version: 0.1.0
              parameters:
                - epochs: 50