hostname: 'localhost'
config_path: '/Users/minhquando/Desktop/MLOps-Service/anacostia_config.yaml'
pipeline_components:
  - experiment_tracker:
      tool: 'mlflow'
      version: '1.0.0'
      docker_image: 'mdo6180/mlflow-component:latest'
      container_name: 'Anacostia-MLflow'
      ports:
        - '5001:5000'
        - '8001:8000'
        details:
          mlflow_client_port: '5001'
          mlflow_server_port: '5000'
          anacostia_client_port: '8001'
          anacostia_server_port: '8000'
      volumes:
        - '/Users/minhquando/Desktop/MLOps-Service/anacostia-components/mlruns:/mlruns'
        - '/Users/minhquando/Desktop/MLOps-Service/anacostia-components/mlruns:/artifacts'
        details:
          mlflow_server_volume: '/mlruns'
          mlflow_artifacts_volume: '/artifacts'
          host_mlflow_server_volume: '/Users/minhquando/Desktop/MLOps-Service/anacostia-components/mlruns'
          host_mlflow_artifacts_volume: '/Users/minhquando/Desktop/MLOps-Service/anacostia-components/mlruns'